# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

# source 'https://github.com/CocoaPods/Specs.git'

target 'HeroTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HeroTest
	pod 'Hero'

end
